# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "0b0661652a064c48f5ec565b596cf3be1a438e9e1bd1de551f16f76172ae0a02628a5cecdd366aaba070786c2040c32113da871ca3a80d26902eb7566a319d6f00"
genesis_address_str = "2LuKycJ7SQwbSxoX65Bu8BwZ66RegDaWGK"
blockchain_pubkey_str = "0278d26405ec24c8bf8998cf767b65c29f0dfcdff3542cdb1de44ed0539e9c9d9b"
blockchain_seckey_str = ""
genesis_timestamp = 1605751429
genesis_coin_volume = 200e12
default_connections = [
	"192.243.100.192:6000",
	"167.114.97.165:6000",
	"198.245.62.172:6000",
#//	"45.56.109.228:6000",
#//	"173.230.130.174:6000",
#//	"172.104.99.241:6000",
#//	"172.104.57.147:6000",
]
peer_list_url = "https://fuckyc.com/blockchain/peers.txt"
# port = 6000
# web_interface_port = 6420
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
  display_name = "PrivateNess"
  ticker = "NESS"
# coin_hours_display_name = "Coin Hours"
# coin_hours_display_name_singular = "Coin Hour"
  coin_hours_ticker = "HNESS"
# qr_uri_prefix = "PrivateNess"
  explorer_url = "https://explorer.privateness.network"
# bip44_coin = 8000

[params]
  max_coin_supply = 2e8
  initial_unlocked_count = 50
  unlock_address_rate = 5
  unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 2
distribution_addresses = [
    "GxQmHiuSeD4qZNPFZaoqKsvnLZ48oepr7y",
    "23EHCCywNmG5sWQwHbu6MxEfsfBMSCGnk2R",
    "22481dKneqmHzs1NbEi8Xoazc58WwRF4usL",
    "28NS66nUjzzWGKf7S2bHFxdfssNzPBLVav4",
    "2P8nPWCZLkCE7BrjuHDNJtiUELUtVGWntry",
    "6Cr1bHEsPYUgFJ5hAhNVDNjush1UouHwqr",
    "29Cbm1jTn97Uzr3mfNxgxdZEsizufp15jxb",
    "Sku4R4xLR3dACamSuNUriYv5VzHY7fyEKE",
    "2G3HdJrJoRBZ2Jc86D7MYoLXQ1uv6bVfKed",
    "oD53aAJYXo3wD9RMZBoseEXh57222oUEzP",
]
