
# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "05d4045854103f8a8938bb701cc4101c38942a180ba02d328d6f880bf37b387c47e95813d061f94bdf5d894bfebf17f933c5fc92fc9d010480765257c3d19d9b00"
genesis_address_str = "24GJTLPMoz61sV4J4qg1n14x5qqDwXqyJJy"
blockchain_pubkey_str = "02933015bd2fa1e0a885c05fb08eb7c647bf8c3188ed5120b51d0d09ccaf525036"
blockchain_seckey_str = ""
genesis_timestamp = 1637895025
genesis_coin_volume = 165e12
default_connections = [
    "192.243.100.192:6006",
    "167.114.97.165:6006",
    "198.245.62.172:6006",
    "151.80.37.6:6006",
    "94.23.32.95:6006",
]
peer_list_url = "http://privateness.coin/blockchain/peers.txt"
port = 6006
web_interface_port = 6660
# web_interface_addr = "127.0.0.1"
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "Privateness"
ticker = "NESS"
coin_hours_display_name = "Coin Hours"
coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "NCH"
qr_uri_prefix = "privateness"
explorer_url = "https://explorer.privateness.network"
version = "https://privateness.network/blockchain/version.txt"
#bip44_coin = 8000

[params]
max_coin_supply = 165e8

initial_unlocked_count = 100
unlock_address_rate = 0
# unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 10
distribution_addresses = [
"yDctMREirofdnxEgZLVJwaZdEb9Em1bJyk",
"L7JU5g8zkfg3q24yqJSojSzRAZc1dbUJn5",
"hY5By3kHpwWp3a5VnDCyrJGtPFAnnPMrqS",
"XTRghTPUUfiz9P3LUWaBRpT7LFoTR9jSAH",
"a5NctjK7wkpXw17adFFSYRAYcJps2FEEhQ",
"2MSeuyaReBbyePioGhpWoQStX8W9MPAZgTu",
"7gbFAfL6XA5Wkpa3VjiwjhZNv4HeDzgrQ3",
"29377Ntb9C2AgumgABigzoq1RdGJDXauBEP",
"5o7zPhehRerBP2JexqwfUAyQiqzQKsbcod",
"2fknwEypYS8WafAd3AJgv6vAm2QtiahU5Vx",
"ANV9QMU6VhDfPX89D6ihnXUqYa3HBGTgnc",
"n5A8jhcpHaFpZfjdZqhESb854831H8QSJ3",
"24EqjDbd4vjxMFTGGT2JSff69ov9wyE9Hqo",
"215c6pRSx6opgrDfbWUPn2RZzTgG9tRET4u",
"2fNCazR5v9T9PAc5XHACnLG1EygixJt5vuV",
"iqVhKSF6EFTvkrXqJ5GZMiiTZZ78uzLwT4",
"2992LPHLUQZbyDG7VQEVasHVVSsgRHnBkx6",
"2QNB75kwvDSFG8s1PcPGFP5c65ZbHbqpJHD",
"D3zMvnSdRvmNQHdAPEJQZ9AKWyo9x17tCy",
"3gHNzic3b76HknZ7XfvyuPzHTxbXEiwkyC",
"nuNNTUzMFasPQcqUcTPUENjkeKGmoVZfHU",
"NKakfwy8ZnQsB92b7TrYeXA8qPtzZRRq3e",
"53haSrFqjsm3BDDzpym6xD9u4HmnkAMUBz",
"2LweX84ZHzGymh7TR2h2XoeEhDo9qRSgppg",
"83raj7p5vd1RkL3B19oNTYYQ77bsR3majj",
"2gfydbPGmGy9RbVfXQ1x4myZ1zNCfTa7DZX",
"qdYBFK6sCsqaCLNYsV3aJt1KSv4hWTjjTR",
"2uokpnd6V6A3Ldgrhpy9dio56yHao9jWwP",
"h8MDjDLH1XT7g9zn3d8FwRqPY2xuy7sCKq",
"2a518YRjyBKCJGJ4tBJi29Ye6uBcpUKWLcJ",
"Wijq7dkEYrjWsydHuM93xnKuLhaFxYMGcu",
"2h7PmyUjWkqZA2GBLzTNQdyGiVx1EkMb9Wg",
"2h4vbLsGMxQKy8tWGahspfGTpy1rkfY28Vq",
"TA3xkA2WUi7yWn5sBJBYmV4s7cD7vpMYFX",
"2gMc3fhVpFdBS4zP6yYsEYzm73Z3qetuq59",
"h8e89GsY5xRR353eefhn1kaWTmHkbLsX5J",
"2NxQGS7basbgiLxj1oxYjgYbWs4vkf8AwqJ",
"2VbwCTzjoZ5G6h2m6hE1937DXCrwjRaWNQV",
"eN2zui8XjzmGTVWjSqKPXeANnSCDskFC7t",
"2JJfDbcAgrVGTufr93DDL1shS1fjMVMiWk9",
"LokK8CfoSbPRtFVcC9kfskYgj1Bp4G7ewt",
"ruxvUQDjBMRtdfwj86yvtZkhnM1aJWoLqR",
"2bcHczBPvZvNCMwuyWheNhP6UgG7q6Bn1vs",
"i8auMsmsTB9HzaRnSK9CyeNeXzaevdiyfa",
"ruQtVXaiwWjXF6pCDQEnDvuW2uCnv6oTvQ",
"2dvLTPaaQcPyv4ktNAMKTEzTsB3WV2LL8td",
"28ZboMGkLqB1i9X8WoN9Y6tyDQuvw2jG2kU",
"ub6zwPXgJQB7GZtqQ8z64LpHEbiLpkW8ip",
"Sz8CL3w5zxhwHxJw7LhGGvkQtvAzPXDLvB",
"2aeA8QbfmGwFoPbBeptyEeTcFtLD6wgcdFz",
"2a7eHg5SPY75cotktByvukQZc3mdckh3x3m",
"ehENxWbxjmjjMewcyZeBVnnVwuPTPWZwcW",
"2cv9hsK2urD7S8S47wNnygxbbYfvPFZ7dQ9",
"2gaKRxthU5tyFntgbA9nsXya6MiCEAhL7MX",
"rX8yQZe4uzTVNj9CpSXNMxn3sRZ8Cjke5H",
"2Z9e68ZD4qqJS6zif3byH19nLVRiox8xuQV",
"rNe7mfHX11HyMMxHauZd4dnUsFjmCxdCJ1",
"vFTjwm2iA2GezXwjKk7bCrV8Mvh6uZndZ8",
"42xm2mtJpQKYy4r44Y9EQEHs43RKVKEqGC",
"MMJcFtXJMhALwMi8sFVu8budSv42bxtzGU",
"v9isRnvSPtzxraeLSE5CGVE1GRVj4iyEvC",
"nydtU9PkDifoX9vhjr8sFNECfVT1Afpzfd",
"JpXSoLWxowxzFWuArYdRUTdwLCAWMf2zHT",
"yNHQuN13Bxz17SoJJsF75dAiugELX9wPGC",
"2NVj8Ud1nPUwTmw4NcPxdC74CXnrYVscPsf",
"CxgrkGay3U1C7wfWmvQGAgrfH5DRQvUi24",
"kyd4iEooQ3PQ6PXdFqXrKmLZit6nXcSbGM",
"Jq88u16oxCWrhR7Qqbjq2fNDvhct3jsjTK",
"5XYNGEaDWWBVXEB8gaagm8W9gp91riocko",
"28PW4DRtSLVxYXDy4RTVFwwVpLAv3nSfhB8",
"GrD1wscPsExwvapNM5f18ZMxWy1wAevEte",
"2Yx7miKTWv3jDRc3d1BEcYcwD7k3qgcygt1",
"gQD2UyKLgyP3f7FbcwxNKYqR749MUDDzyC",
"tYQwBiBVooR3DP2aEEZkxoJ5Q16a6K4LzE",
"26g381dGaPFYrETPGkecxHCq4dix1RQ65mA",
"VsDoJgzpWGHjJmE8zL1gCw3yiDGw6NRhHH",
"AD1K2XvDAKjTCKqPqo4wXXMp4Rurke3qyb",
"MEqcutEoH2cLoHkeGHrQvtFrGssmrPoyjX",
"2Rh9PaUxPsZuHreWxyDiaYyPsAoRbECrdkQ",
"2hKuEKXE8oqBuZym4SufV87aPGLaquH1s1X",
"j4aJAEuRVYvDpVUJRsoQQUDn8hSaNcKDi",
"kFW5NWcRVCpzC81wF4P54My3U17oAjWi9X",
"KPWyqBC9h2ohiarkmUnpW1fMo26PSEcWFn",
"SMoNCreFK4CPcA5QoueiooAqMK7ZxgKbrG",
"2dqaZ9HbnYrciV39oM2wSBU6Q4vE1DTztKk",
"AjTkdeFkEVMbozXf2PLcHWd9pXpmySXRSb",
"x8LtADzaXaRqdoKMNucWF3Tf7z7YNSaCtL",
"2axwNbsH5GZFAFC5GWSaWSPfVSwztvDUeTw",
"Lfxwte8Yuc3UQiXqubTQKeUaz7PzuF6iSM",
"2eyer15n4pRaJZff6EBPpSQjKfvRoAYfgKC",
"2idCMCabCMqgtRWHZMjYyeKR8uKnAYxT6qu",
"XKpcTs6q3anMuKLvprphLEMHvwVed6B8sT",
"LhfQcHB8awMpujkw2jscXcDvt7RjXcmeLe",
"2heT47uUzf1LkELNE7rxXDS5mXwqStNvAeo",
"xzfAZ8hMmdmeYYLUGcUT9gu7fnU48YMDZg",
"2ijSeCBd8xS54uKrnBdCvdjC1rQBZrUZDDJ",
"2DVasvBbLPEc7ayaepcug6m9HrDQCdcVSjf",
"F5WrjfzSWJBq4KwC7gMW3em8yuvrz2MFWT",
"wt1fuksebq3QddGLuq7MLcHRKBuHnCUsog",
"6kXBawXVoyTTSffYNCEQLCFffJz3XrE3Nv",
]
