
# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "07505945fd5224729ef9f97a24588f8cf9b9a189a7fbbcdbb1881d3c573cf06318ebc015c3ac35b3f9379a6b3606846e232897b4e8a9ceb13380f845a936065000"
genesis_address_str = "EvS7nJ6ckPrjK5G3dZeBAVAKjVRbeCSF7a"
blockchain_pubkey_str = "0366f7e3d2073911a61fd479f7737bd18b238a93c3831aa24b41d31306bafd2be9"
blockchain_seckey_str = ""
genesis_timestamp = 1426562704
genesis_coin_volume = 200e12
default_connections = [
    "192.243.100.192:6660",
    "167.114.97.165:6660",
    "198.245.62.172:6660",
    "198.100.144.39:6660",
    "94.23.56.111:6660",
]
peer_list_url = "http://cantdoevil.com/blockchain/peers.txt"
port = 6660
web_interface_port = 6420
# web_interface_addr = "192.243.100.192:6420"
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "PrivateNess"
ticker = "NESS"
coin_hours_display_name = "Coin Hours"
coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "HNESS"
qr_uri_prefix = "privateness"
explorer_url = "https://explorer.privateness.network"
# bip44_coin = 8000

[params]
max_coin_supply = 2e8
initial_unlocked_count = 50
unlock_address_rate = 5
# unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 0
distribution_addresses = [
"6FW8V65zEiPSv63iMjG24ZajThnxUAti9w",
"2eZurMJfDom89GCoafQ8D7aVYeEJMTXnwPJ",
"UerZFjNenJcvtACzVnRxR7tnAEXAvJYGdh",
"4wk1r7XRJsHymSJ5qJqsvBXSEyh4Paf6Wf",
"2cgFLhAN8baPD3DXEAKMNy7fxHThf5TUcGJ",
"22wKVJZqUKd2smrrhosdY9FSQiG3nZ9hAos",
"29yxycgsZHFbmSw4nTySkqntrhAaguT3azL",
"7GGQ7o6eKWFMm6ZwZREe7FNqakJXuHygQN",
"2tVDk2JDH3mLpzcmRAu2nEEkueYKNKeSKm",
"7Pu6cB8RK1V3j4r9vaH87MFdoGDr9AaDXN",
"23DrSZVRcixupX6qsnWHbVYtyRKCzuyfEEW",
"2WFkfiaYismAfq3JMmvKbnPNSa274oBNbdP",
"2cqgNyCr9MyYkpjq7BH1H1s57a7UaE74ycx",
"2De8U6jomPYdBF6U24dWQjQ6sVhncdkkkvy",
"PgWkTzxVRuGbnws19TDt5PX167mxxVXXZc",
"ZggWcDRjjtQ6vg68UYipvkvDUD4nUBNFfx",
"qm8rLJGLuCvLeu1QM8FUHi3C5hgG1h2nav",
"YxYQSDEcUXyVQizC9VdV2xPnzit4dwtatN",
"WewKn9NyTNQcRHJvq5jobCmhkoMUgr6Nvd",
"2hzK5kKrZ5n9KVSxqz81rKx9QogJv7NKWoe",
"zeL6KCwb5uwG7EaXdmV6ydkV4EhHnvzHjP",
"gAq6b5YBMofa5ZbXByq8RRLfSDGSLX37c2",
"2Cm2P11H6o6ntLEaF4vQud4VGYBxb3JNQmn",
"2Ct2qhH6LMwV7zSSS21kfpLgv6Bag1gXC9f",
"o94YDmksQnJs4t69Nx6rYy4dfeKf2LV6kw",
"2V3cRxyCJ2U1qaXQB8ndGEwKafg8mQvAQ8k",
"2faBn3hEr3vhYBD8QTMaLbAP3mJtxP7cBzq",
"2RbMk6Vwt4BSBuXUuvFivNnQN65bAMSx4E3",
"RS3S95JpKpwbd9vN5a5k5atdt8N1u9nWqL",
"2aXwPLBnXCGKFe6tk5qQsHG9CyACp3BQEpq",
"2TbRCCSpUmf6cDA1c2Ho9mADq3MKgmv345f",
"NRfEMHFumi9Q2C5MHoSNwhhMFjwbhSHEPh",
"2mgNRqb94DTf4tZJG8CNz8MjnkNoFgpJxve",
"2LAn4pZvpfSwwss7K67ctVK4sAvmTC36TG3",
"2Gszz4ZJQLMCmzUG5mquGva3rnc7fjKVxPK",
"2YsbUG7hbByogZy1PNAr968uGWU7AVeatNZ",
"TLAua3knz2Tu8qSg8a1kSQiT925nrbyX73",
"FRJYKZCXfiDSZXPHQYuhJLwmLXc1FkCjZm",
"21ykhVseAdvNVQH6wfHhJczW25QpmfgNvLz",
"2EcMpyQyQmd1K3WaT9y2aqQ17b8qz4oWgEu",
"eTk6FLGaAdkXRCEgAasUmn4AxpidmrT3fj",
"2KiV6hDTvfobGLFQJx1U389rEc21ptk1F7r",
"X189WXGMUv1pXQNJjS1yRHiWpiT5c3Dc5t",
"V5Hpn1RAjSNK1PmTFrDwn2cian8JfdgWRn",
"z2Bu463yqGhqJ2a23KAGnRruGSRvfPddcc",
"GZE4sw61dpEFxqyeMY9EeR2UCxb5Cam6Nr",
"21AxUf1LVYR8oRErsVyu5Vm7kPXuAwpFqYG",
"GrbtDVyQie4uaHobKVwkC2ddXsDQfywC1S",
"2Wsz2CTTXA8TJBUUJx1tQr5DkUxK6FE4uog",
"jmPhjbpwTPN9EtQWcJ7tYMySEpRYVXRggD",
"V7rLbt7Cq3ps8iSSHdXA4xeNQUqpfxsTmF",
"2LxWvrhNrxu2UFLz8pF9pMqPfz49DaEPNW1",
"1PsnRYz4B7A2DtXxVJnWS7guCaBuvKbh5A",
"rtNmHM37WWR5XCiTU3zBX8Ax9mFUMnVm22",
"VZKQfHf7FvRGQKaLtCh592ePx9iZPNLBLL",
"CLw913hUSzaufMRh3bxDrRRpf3wqCjyRa6",
"etkkP1qF33o1HKG6e99XzzUzA4CdEJdXzF",
"xd6KFrgd6d7SxibKsAf3S53d2D7o5FDdCp",
"JnaFmQz7R6yX7o2613H3WKFAcN9C1y6oj2",
"3RxwASa6bVfjvUrq4ez2tnGDXU9PeDbRWt",
"2d5r8YK7wesgWANUxgHs4aB4pui6cMmSPyZ",
"LL8vQy1P1kogWnJEjtL9Gv2QmCLtNRhuCi",
"2NVyDaKe9RYooh11cwqPQFgc28dHPT5UHi9",
"2HKNjLh41V2nK2djYFC721QbHot8g9JndJd",
"2UqDvjrmkJyuENNpgFDpWRU4wx19stESak6",
"2AyEtiiH3VUhEcPmnjZAzarfbH1i3b4aGAz",
"GLXQToLHyWwUC9MHVoveWuaZaL4WVpc5pY",
"gpUcw1hL5gncRhnsbEzVvqohF6d2DLZ82C",
"svNuuzUg9W8qjW5it2Pvfg8gGqHtdt27uy",
"u9SmdoRdDTZgErgp9oFKosT1APeGX4go2z",
"Ctbq6u3caHuQXKWGUTAJufrDx8bKsbY2s9",
"2ZUzQp85VTk4wbWMLiwH6tD6esuvDa8s6vp",
"2TV8zfPn1ojFeQLz6xB8182vAQJL6yf4ijX",
"2dYLabXzU6WMWRoQkviN8GgsiwkKgbpZzDZ",
"2RiHvv8KqgRjHUkjKtuVnRAhzDjDsm2Ette",
"kT6Jq1sTK63NjogtGqJJnHGcsyLdCGM8Ev",
"26nMcn1Rx4hdadfHo8WRXbH3DfA2K9dBVJa",
"5oZZxdU7WRxA4zTLqw7gDxwejcBjacyExE",
"2Pja9UmNHwrJ9VCgnwuRzH7cngw6SSw1dhc",
"XCHoRZdwASxZJbLEntVpn4JpKcnLZNe67d",
"koTXnkqoatRbEvqcCTtsNfKijheHTk5q9c",
"Z7NoBkPLvAVut47ZEj3bfmdS8f4dtamSrS",
"2Ndvd5vXtDTua3N2oopCGLPpiUxgSBX2FiU",
"2SrYjBZV2MJbJCj6SUqHzkfHuT9mn9j8PHS",
"2MwkWesZd5HjXatAUD2c6SfakLBsxk8a3Jg",
"baXueatW4vZTGVofA1cgmkMz5nXMSTsyQu",
"mVeNMsWZLcxQXfreFaQgSoVpUuVs8g3fJb",
"26wVgjzA6g9M9ydLbmsKVj1qb91ZenDu7mF",
"28wsQZCtMx3urdHdiMgispkWz7HMUqNj9bb",
"9gkxN78DZhoGnYYpCrNkHLtDZx3TEaxxjt",
"2SiU9c6MCn12cjbpJZ65mcT3ZfGfFa85nET",
"29BKFvjLtR8vpEw3wi8JFchckfW9KZZDzWR",
"2dt7dThRmdRL9amXG2j1dG3CfRVZqH3orD7",
"zAsvE8wqvcLiJ7ouxvvF3Vf9YG8DjEGzEQ",
"z6XEAbx6iY6GUPsHXpEpB3BHCRnEaK3UV3",
"2TL19VJAHNRfoLTSRR9t1LHVKgborAagg2n",
"3xE9Da8h75tfJScNVTD9xzMwEcNZhTftd5",
"av8QxutWmTC8McC4dm45jcv3qGztvMk7s9",
"2cHaeVQnKdSLrkcnNFeoX689QnfmouEFLWq",
"2mkfGa8yBHsWAEzrb6gf2oDPn5JgadQLk5S",
"2dAEDRXCK9AydCv1mg5DnLCt8WoVp479jZN",
"2NGT9pcTHhQHmqAcKtAwzSKJJNJr3QMvUGT",
"2QGUVZdvYSvejRgJPzsDj5mccZPARUmixe9",
"tDV2gn843zp67DUjfwQ3XCSfZ9MKXT9JvK",
"2ZMJTEX1RkZczdv1dwYa2u4wXmUgxinaTrN",
"2R2wrcz2nbRjxRRp1iM73LYgDb7HCsuAQ9c",
"gVXR5hbRYeiJRfBkUpapDZA6o5iBnaZzQN",
"pH5wyngg6r6xNDhcEk1dtQTx9vLZZpT1yp",
"4tBvBP7PsD42jKUjyqEstQ7rH9Cpz2xb9S",
"2AYxdexMVqRyWEmWS6szhjBECmTo9KuZypE",
"2FGQSFX2AEXtKE53zFss8arJtgfK3t9s5NW",
"t3N5R5X3nrabxztRCxJHmrRtSdocaPCpj4",
"3AH6n71F5K1Gjr1rMFS42dYXDEf42rjp46",
"72WxcdyKjxdZrWebjjeSw7ewtge75RQTCf",
"worLbbK2kEGCETgSFCMiEvjjjnRke6sXfg",
"Q8RmswAM2knuGBC41mu8mKMGKUfF1EKF3C",
"2E977KBKvh67jpmt2bfU9gfVwBbMVXZUaiM",
"2mbqqeitn5oSwTcKmX1zKAMCGsDuGMkaYc3",
"G4v4vvJFYM8MEirNGhnc4WDBLtcFDLm4fm",
"2NngMXCsUJ7a1JgXyke4BTKjonyHEkWWsXs",
"2AoipUq5X4skX9RMsMFJHqbSm6gUevdYVUc",
"jKZFPw6ko2iK2ydG7TSmz8k2PkSdjSu1Fo",
"2egvQiZ1XRh1nYKXhU1Eh3eiFmWvcBxzzgi",
"2jF9B76WatEwm7T77jCizw8piubWMDfxM7n",
"2Lsw2V7o1nsGmjwirYYXq8M8fVmPHFPjJuC",
"23n2i2tg3ynWvu8aRRWZD9AKARKffKaVLzu",
"28C4VxYGTdrPPKNCSGkHsZFWrfXx3MLUr5v",
"V23h7XjiSzsd2qYUUG7pcb9VvnFLqi7XVQ",
"tCgamTe9F1sgLiFBBcs2c63m5qD9bjGC5w",
"2f9W8MDuw4X4fBtz5zpdvEmwQuGtgGmjjcB",
"adC61JjNAkbhpkgRGSmMTyp2H4ssoTUTpf",
"cgZaBQpu75iN34VhGkDLukg651G25VhfxA",
"poQYq6cjfvYwTXPtde85h4zQjt7ZHPtass",
"KMqaNqTegCgGgcA9v36TiN9LQymC9C2JrM",
"2i8wz9PgfNe6TMvS5ZwKEd9kFHFf2CRKHun",
"UNaxF9QLKYgtRbNUFBPBueqYbXs6Yqhkd7",
"2WAWqNSh3deBLKi99GSaoVP2JeXVjuBLpfZ",
"2fMoZSdNtX9ghxJHAynfyU8aAgShfomRWRD",
"2LUxrdFkzRQXcRzCvmXLy5N7GUGckNCBtjq",
"21dW8xYzBhpoQVkULTjCmRNtbNW8px2imMJ",
"24hDBGsUaCxqQMZ48jcap6ukQwYqM8meFFy",
"aXjG1qkZMsrPnYS7ui3r6NmAPNVrDQwoCD",
"s8c5uvn8rzNWN9ci2uMms1p6FEUDNVoco7",
"5qiXfyYQJfXX725P8Q8a96WAxx2WLrQqNc",
"2R2B5vwexzezLkuiYnaV7fZebdkoEktqe6Z",
"2VyuM3r8W5P76V5Xm6aSuj3sSDj5pQngRSX",
"AMDbLb939E94H1ko68povMaBeyZm52aK11",
"p3jhkNEduEmY97YiYDFQj2sgBEi7cz4Yk6",
"4NrfjDVVeZdbxtCicXKChBxAh1XYfDuczp",
"nLZeKPH6dPF4h9zAdJVA4Kjg1XQfW9duUv",
"2cLpE6DeKcHnxZWkUigX4oDGp2VMLoFc1k5",
"2cqCeFc1ZpxZm3HsYMD5nngofLh9zfT6mcQ",
"XRLE4jexfzfJ4AKFhAw75vR5yJrHJZKPbK",
"QmH1fAsbceYYRY3EEaSM6Q3NARXQbCCnsx",
"2KcJXU6zNzzfEcGnsaJVuuJEeff7vdU16Cf",
"7VGcC4aWNcvgKCK1MtPM9ejK9fUeZMpC72",
"2KUYTtYKS41iN9aj5TrccAoR5MZUCtC327T",
"2hsDbeVUrpyYk7mcpFzfx4cNnp8ew4pHRhw",
"sAQjdaSZHjaL7Dc9rxgTVpYpDuTM5UCC8t",
"sz8LW9stzKMCcCLKN6Ytzf4TEe2wYA5eQH",
"2KVpkiXaupzxyYHUvD3Qst5RPDapEx6xVzJ",
"2FqUk1mVN6nCjuHKZYLm7Ki37wuW6cfodQK",
"Js7Pqsxku4V5PzzusNZGJ2atTnswhpGB36",
"vKTJsM3Rqjwk24715esLqntFfbxAZta1P2",
"2djdpSrZ69sxG1EBH8x4g6Uio32xgRRhFMK",
"mc8ccdTDYKFSnTiAPxCTv8EDFsYjsGkrCY",
"2RvLzbw75S2i2gPrab84b821moDZskbrg2V",
"2WBE1Ck9RrNYq2dQCpNduXtG5EGKw5gYkGP",
"2DiE9MUEUTcGccSVZBTPeKh2cnvFBXUAr2w",
"2kyLDEZJrNWuFcGrerb6rDsnHBcw16ScVNy",
"3sggfADzp7VJkUgMf7JnB4HyoW6cQTa5tb",
"TgGHDdACHv8fBPzZUoiimW2PBU9tz4BkAW",
"9HNoC7onLX17qdrxNrtrQTJCW5sz8zbRBg",
"asp1sSHbMcuf5pYDtpKUp2i5yrUhfoZrXs",
"NcrWZ7QZLPFr12FWKsFcrWmSJGjBfE8HDJ",
"2YUVpTKATC5Y1ZU34CYgFED2DbmJXqcJQzY",
"2emkxseWJLZMjMuEJ2qKnpJwAZ7RGRTKNgg",
"uHYAXV5UQwrkaFZYj9inJ8hhreDb4ALpws",
"2YFUugHf8NUV7jwtcJ8ydeA47EvDGtXmKDv",
"BGU89NFwTkYd3vEge5wUvPKZnQfdKtkqev",
"StM5zL2ZYXdUsTDp4SDfDtioznMn1ot2Ag",
"cFQqetdtY2x3GsaHixK2nV5xXmwZPjMc2T",
"23e9Tnoi9T9LpRbuHaYF7sgRVEPxmwvwzk2",
"2hSNHYqnDdykMcn5ag25igvJiepJeRHeX42",
"gmnyCKvN1PAcFwR5dUTyAMMhyyoHEUrdXy",
"hHCS8czduiaYzWArhQLnQoCRxo6xdFDX8z",
"VAVH7pAx2popYdy9tjvRpMXWUPVcN1zfFL",
"xuKSMhxKDQ6p8pqEn2Ur1JSrzwwKf98FBU",
"23BbXPs7JLLGkYbGoR4afaWnHbkry95EfG7",
"QnKq5WYB8QzSXqVDgCr5N8ZNjomFqkTieX",
"2PUbP1fRPLp4JpzWdnw31DjYJsvHk6ReLJq",
"2GpYAXgsmPKrbcU1N5WJG3QVZAJPuvuvGMZ",
"tZiit5k7QUPdMtvBfZLVKmdv1EsM2nmQWR",
"5UHgxnZddbCyRvXAzmzHasQReHxrYsBvQg",
"2Ji9dJEHq6zK5bSk9bswHYZf7BU6t3YdV32",
"XGfy6CrgNKyxQfS2z7pu1tmC1UbqSGoFgg",
"NFynQ9XGCTb12R1iiP9uxFKKzShgQgdVGJ",
"BvMtSSutFFdj9s4mKqM5rvFKuounEAwZDY",
"2SK8CRHwJSpsMrz1ZYwzLC9RTRHmz2Eufoh",
"es778opWJ1b4oVLoQ9mxYYduxXVeC56CpD",
]

