
# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "07505945fd5224729ef9f97a24588f8cf9b9a189a7fbbcdbb1881d3c573cf06318ebc015c3ac35b3f9379a6b3606846e232897b4e8a9ceb13380f845a936065000"
genesis_address_str = "EvS7nJ6ckPrjK5G3dZeBAVAKjVRbeCSF7a"
blockchain_pubkey_str = "0366f7e3d2073911a61fd479f7737bd18b238a93c3831aa24b41d31306bafd2be9"
blockchain_seckey_str = ""
genesis_timestamp = 1426562704
genesis_coin_volume = 200e12
default_connections = [
    "192.243.100.192:6660",
    "167.114.97.165:6660",
    "198.245.62.172:6660",
    "198.100.144.39:6660",
    "94.23.56.111:6660",
]
peer_list_url = "http://cantdoevil.com/blockchain/peers.txt"
port = 6660
web_interface_port = 6420
# web_interface_addr = "192.243.100.192:6420"
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "PrivateNess"
ticker = "NESS"
coin_hours_display_name = "Coin Hours"
coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "HNESS"
qr_uri_prefix = "privateness"
explorer_url = "https://explorer.privateness.network"
# bip44_coin = 8000

[params]
max_coin_supply = 2e8
initial_unlocked_count = 50
unlock_address_rate = 5
# unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 0
distribution_addresses = [
"2XqkWfGNxDaZ2sSy75JaYRL62i1WekEitQ4",
"2XJVrtDr2KaU4MekLFV2VkNeNAhaJ15k9km",
"h7cqMpaENdYZaAcWLm1e2N5Cq9VABVLjGx",
"xkBZqKCxyP9K2iAV2wbdFxozaDUDMbMYzD",
"q7uQdWt9kPkd8da3zaVAN1ZJpkpvMpiMq5",
"8A8ZCkFJGT4iRKrNXzXSGZr35yWpDaARHw",
"2RSUuJi4e2GEi9dQGyCBFP89FoZK1LSL7cH",
"2fouGAwa1okp3PJiB8u4ybbTEKQ5P58GRfh",
"xMmmszZButUKxq2qDtxeRGAzu3KECsezs2",
"uBiAJAqXZJcs2WPjQ9PcKPJudpjKQtjejy",
"2CGhHs6DucRXUHe5a8aQ8HMa3XEd8euZpEb",
"2Xqv1te69wtcBmwvZ97RwVijsC94LssJ372",
"2K8NVSCKEKDU9tTtmve55uFViMbVr68EAPQ",
"21xJn2RZA6AZUMNiEtbT5ozHc7Zkqh5ucXd",
"2TbiQNhn8yQhCW3EJHEXeg9J9DHUdaGAPU6",
"86CAvasWAVyUS3r1CSHmSj6gBmtP6E7C67",
"2KGcbBstvaY7Axy6XG87ytr6WtbGgPNxVin",
"2HLGWfk7RTi95tsL2yktDQDRWatgeQUWkEs",
"D3S9fJHcaDTwcbnHyLGMTRZPEkWyX5713j",
"gqqhc6kX753u13EBYdetN5R7cUVtBvFFQ7",
"2bPo6rAYkycHWpTqY6dciPfeqVWTb4X8qpV",
"23e7mXmfXYhps89697hYDAAbqb5SUfgk6PJ",
"6GbqbJRwbLqFPnmwBaBRPmo7F3PNiiHkQv",
"PaAaBhvSn7NFfzei8WQuAUCBEg9YJdezXV",
"2L32yQxdqj8tNzkZ7MA6hjKWUdRwQwrAm9s",
"croBtR69tSstvzJEdE5eesZy2K2grA7Mv5",
"2jk8c8pC32Q3jifZ7t1WFQEPHFeyccNzvAg",
"xqsXpJLThoZdxCxfbNmssgoHdH6jXmZYtJ",
"KR5rt7vgCjs9Dwk96xqbvvUJU74mXA1VgC",
"2Ccksz24V6u7GGMKcCWt7qi5KEKC7P6zSwc",
"N8N3UbJi1GQiHgxnes9gM5ebD3rMsTLRvq",
"25oWNWGu6kcRkFZMtiUGr2ehWdcCLbYNXKX",
"LddFYGY7Zy6rrjC6wA5RmEacHbgHmx4n8T",
"NfjxDxRT5Kwx6je4WB91XvoHTNF9Ys74iw",
"jXLCUaCCQ1ytTysfVWVhXzpAywpUw65Xyz",
"QBYAXHCsQggAR9pN2xsr6yEDM3zc7v382P",
"kJpGmn6tGP4KWAPcoNLrw2x82Z7bgDYkh9",
"22kzKD79nM7RNNyz1RZm7b1PUw7P4XWrQNR",
"mTmQ6LWZmTrpwGkGDSw1xQ2yDD2s4QGAPU",
"26CBEK2eYCwLsSaW9p2jBCJXFzwwPyaiKj",
"2UJuddNqAVyHAhsnji98acbaFCPEw6Z8T8H",
"hBBB3BmbmnTTgfNoaP5AcUDaQ9YSuAX5Nq",
"3vxogVBDdJdo6jbbJ2iaZLQtoNN5neKZ9K",
"2ZzJwt8YpAqd7VWZdpLpqfkL4SGqFCYytZ",
"2NgHkkgB5kLcmzYtQkC82KXXsS3CVvdPKX3",
"jTGfvru9vCuBmUbvLAhMoFoi5DMH3uqcYR",
"2Vyn9CGdzbyAXCAwxohR45L32SFy1Dk5P49",
"2FhCZkuZxfHSbKUYYw19LhZ4wiCWHGVNDUZ",
"2Dk2eiNvjwkhmFtEFNJrNPPBGuRZWzkMr6q",
"9FAqx5zgm8oWgjpri5noGgaE1t7UHHib6i",
"2Rk1kMXyaQEJA91zQqfRTwYcnoxqVDupChy",
"2aa45fPgZjvRWsU1rWT2NCMYwGtfct6X9Gv",
"mbGCKgUszP8qNZXqneDqLXT5ApVLBejCgf",
"2UREwweE57u1yZhCzYMyb5hSQrAyqRnjg8n",
"2XzuazghsMKnxZazrx12dyBzX1fiFGAM6mn",
"2UyGSd6wcLm1iXoo938ZNis1CSZuWG5hw5v",
"2h36okpy6Bdv5YvV633Cwd4Mhvbsme5tthD",
"cw6H5QBBPny27LBEExdj4XypAUX1GjJW8c",
"NxZGdio8fjH761TraE3tjX1jvfSHWTPAht",
"2TvYtQpuD8VfWzLqWW8zFFed26wf1V3Qu55",
"2YdfM9WxYZgt5QpQJsbcenh8LLMqiEiwRVT",
"ANURwHyvLJw74HQR6uSgUVmajiE3fAdNDG",
"vzxo7eydMohAieKpj4oopFFVZsrE8WsCHM",
"b6xakGgkZF6N2VfVFZyi3K3wQkAssSYpVu",
"hmobyPPcG5zy2hA2bPrfQMegU1SAXHtnfY",
"2MwaNKHxNtKnMJRSVReYSZ2QKr37dojxDWs",
"2DVngMN1hRv6wq66TJge9dinXGi9RxasMQ8",
"212AW3T9bc5w85AJiKGTEN3wSb8jxkW4FbD",
"TarL5KQCCHXKDLQopkJEn4hAcRqtHED6GS",
"XtzUzwDq3c41NGPzUq5i7bt3wHVpCJUfPk",
"bfXrJCehudvT5hd6UaKJvtcMugM7QooTxW",
"2hGucjXqYoocBZKvwTFyEhp46ybY7jQXuj3",
"bKV5iPEZNrjF6yvCMvC3d9nijp76VJzSdw",
"6jkv2genrgX77on7NWj6urFdPdWaCtLxeZ",
"j7267QWXPRaLGsxFXqeeu8Gq1nbFabboNB",
"eH3HptBCGjPeA4rmC9NTm7yEbwdZ8aYQsR",
"2BrcVj8Jt9HSF2Ydq5ypVgAAXJm5VwQTzSV",
"2W7oZvNsgSUCTJi52bvyr68bbyufsxCHAS5",
"weFczkAVCtQbHxkmSxwBXxWTwWWPiPfWQh",
"DTT5NczyRVq6xo4AnjNEuBFnmLPnH8o1eT",
"AKWod65huxATnG8AAyYPEvU27phCUuuTbM",
"27522GytpQZtJYk5zfpLAYbimAPBi6EcTec",
"RczBhQzEhH5q3fTEMxQ36jGFz2TmkshTRq",
"gZRcTM354iEajLSZUhRJ9dqUza7vwtZkXH",
"29giCyXNApQBTnN4F1qfM7L2N469fch1fwi",
"BtxWZrgiNdJarQTjtsnca8KEiFwsoEhdy1",
"DakZGr4xYtQX9BctHqrPKmyAZ4ocj4doiC",
"LWqcrVM7H1LDTcGRAqTfN3cXczXTybhfKJ",
"2gfBoukKHiXfS3i23bqqKWAMUuQAeqe6Tyo",
"2b1hj3mXiXGqRDrQg2mEMGqWehwL6EJYS4G",
"4FJWFEPusR2VE8Heyzhxc6s6JjjrLv5AVC",
"2Hp4heSgCne6t3Rr195Bq5VexBGbdFfvVF9",
"2UtbXY9boa7bzod8KvqXX2Rxo9exQAzGsDa",
"2NHyh6PpZNr8tMvJtjg5sDyDbFNkpxE2Emw",
"NQqs4SSZstRSzZYJdn7eRpc5HkWkLNQNJN",
"2jxwoBQAV1w45Ra7KU9mqs6AKnQiiU2sBY5",
"25tETMQd97e8j88NAhwvtgRz67awwCDSote",
"sUp9haXk3SgU6vSTHgZkUjAdYQrsgqvE3n",
"2DWoWFxpYdwN1U7Zbh6cihykRoxFahYxKr9",
"EvfSBygUKnPxWtd3NjN5iZV1iutNBEyGaK",
"6cUptajVGywriWqCskxnLdSQiS348vUhrR",
"2d6vKjc84o5fFjAwtbvSC4zCcdc1xjs4xvX",
"nfp5LiXiM9MFz5JsMUN9Et6EHJ4GQ8suZg",
"25SkbeiShAPrc2147SS64dWms8T7XwCHBJs",
"12DJXnRBmjgmvrfFxgxLy8wK6GeNyuvGFy",
"2JNGfRYEuj9SKWziX5t58uCGmrQ3ABfRP3D",
"2Y9kZysC3BDU4Rp9MyRoJ9gaF9ssLrzpMsM",
"7havyQKuqpr4H5aZ9tc7hHXf2pbQPSPwVi",
"2YB154LgGjBA6CP4f73kePp5HE8KUL3FXxN",
"Ux8uX3deKi2BtUWSFKbs1k8qjoygiMvixz",
"FS6c6FEeJykUNUuRfEDkmmdnRpeyKY5AKF",
"2F6mih6DiJuVwjk96o8qgZZYip5GMPPVKF2",
"29AFqHM3xB1xXAAAeT9XSqud5R4NwZJtTLG",
"2hFZmR6AzZMTJsRJHEMiVuSM5dPYm9YYd8K",
"2X6jNX2ws32Z9id8K9p41xqZ7YoCkzRxeUa",
"29eFZXWEeJybPTgz36N27y73bHTknvYFaze",
"uswESQjyUGmU3eWtDSMsmT5ZjxhvupVhd7",
"bo3ETG5MCrZhbHBvRRtNFv5hXG6mtdWrBC",
"TmSWmUyoFBdT9ukiCawq8oV1JtbwU2uSAj",
"28Nyjy1zNNg8EP6nMKX99wn6YKAT825frFY",
"eKenpPZ1opDfVAUvPj3TFhASavnZ12NKwR",
"3QsJgi4xxH7tuh6JKNwobByKP3mFFHxfDB",
"2Zw1kAVsgeLDLcctRUEM7JeEzvaT7aHn6PL",
"2C7gxsn9iA9vykCT5N8tJazExZPPucMvqs6",
"Jq9saaswbmYY51PPPwYNj457XmeYn4BdZj",
"hpSkmdZydfFj7k67s3d2CEbgBgQREUdutP",
"ASyrKcviJu6wTd25RWWwxVqC5Aw3tDTgpq",
"RUSXfai6KHTZzYF5hTKyES1Hjg3gPCe1L4",
"XJkegtbqAN9eFqaDt9Zwh8WjESQxdtugtq",
"HUpud7avqtC7aETwSmjarD69Zivb7c9C24",
"ZaGS9cazva49w8L5QjheLnatzCvQXrZGu9",
"L8WZvXrZL74d5WTxm19gKhtKu49jqumu9T",
"2jypbXJxV5petxu6TvUYEwXV1B8X8cuCDZo",
"Go5gW5vgtvsYxUeCMWiWrksAwaZAr1XZHW",
"Wo5D5PwrW3YoFLvWu3pYNy5BARRd3U9JZK",
"27N83GxEh6WKV4XV8fUhKqVQKAHgyjfFJxu",
"29M4xStcN6zL2aRikvFA2d9wj1AfDeGTPp6",
"pjZ8rWtiD2nKhWghSNodnyXjjPD4oqq6HR",
"QWF4WcH49sB9HPXzkFZHtD9wehir7N7oc2",
"23rfJ5be247XRqUYrHPTBJZWwVu6N55UQpB",
"RpA3azCmWQhxVSFCJinucdGFQY58Kx79v7",
"2itxJD44xX8DrSeew2ue6nxYvoHKgJJdRgZ",
"jrMgM1z8eNDk1qBPcGT4BGoWYFSXr1PMji",
"2iEmvCSL5MLL8A9txVWXy7FUFxnvY1pnseS",
"2ej2HmNnyKvUnt5CicrsGuieTLGxRH4BSAD",
"22GEqSS6BiVDYzNbwAXhy8KBbNjxaQWfdt3",
"26Nwj93yDUANxWaxgAnkoZCVRamSacoGzCw",
"2VXUG3Z4n6WejSAJ1bvbM3KtYw6xZJtiML6",
"zsNpx8rEn999eBjbEbJ61k6hdsszoN6NbL",
"spQtQKLC2PRrPABqEW34DnBkFwF5t6tbZJ",
"Wbyd9p3jMqKZaSCrxtKLRL9CKewUEjbj66",
"2DcAW2Ekh8rTZ1Yfq8M5irhhTn6pkCfokwg",
"jUMYyorxmEk6K2BdBDvjwa4Lekz7RbSXgH",
"28FczUwi9ysd6oviZSzwmpR2v99yWTFAXCW",
"3CiDW8UxN2JZakExpoSTJuWmWDdotwVQWG",
"2k3sEojcDVY5BSgaX5pQFLzk9XKbjsUd9ea",
"2X73QQQgSrwXFJwJhzxEHkcZou3WM3cJfxN",
"sHgMiGNoPZSm3T4PwcfwuxpvxeXRXaMpU9",
"6Ausuey5JZGMEcbHU2SdV5iKGaEGT4sbhN",
"24BjrtNKMt1VpJWkcUJTXZaBZnbcMC4VqhG",
"j8GpRNE4YVHFu2gHuKpDXT2WdCjizzjUvG",
"9oRww16pkkKvy2tdcKYBCEjrQG4AGUgR1E",
"25yjyTMHNpKDfiSjHMRpP7NP2Ta2Mi2uJP2",
"2EVSPCMbCTp2cikBToS5DvaUXJh4y5eazYQ",
"2NipXrHnFwTdV284hwNUmWrmDU4wFQHPLnd",
"2DFCndrZRCUwRwkn1RPf7iSMYq4xJ3Nbsgg",
"pWbpnFPfr53zXneaRAzwknnAUiWcgMmdbg",
"KSCkmGrbsSVssPkcawVV8AZLcvfjrAqAXC",
"Ha7qey4rzV9fp2PfjavQ7WvpccicHxBZmg",
"dY8xMczj7Jxx9jX7QL1ejAmFFavbJPHCe5",
"8NGTjLn2xZygAeQEVkwt745RTUTUvNamzJ",
"2irg2wVPW9RaUMPCbgPnETqqoCeThPcpL2i",
"nLfCFFNVzh8znVFWTeBKVDBzSsinDTbZP6",
"8wkY1a4KQ6Fgv7TyXEdGXFBf99kjSZpg1B",
"GT9pp87So3r8wm4A5sPZ1w9QUP5ukdxcG7",
"Y6mCyFgiVyx9s47hkPqnWgVeYwgaMJv1m6",
"q3QbbdgvvwWeoab2qwbUdQnZTMYdYpsiZZ",
"2kbxqwAZDvG4YUFpGy5ivhGyaR2xhTtaAw1",
"jwL992usfCAVZVFPuVwZ1kz5sgY5kn8ATx",
"2BsJ9tADx3L1LkfvWvVKhWHYxdhgBrh7qWo",
"2K1BJkzK244rhj61gftLo6xhVjow86YgQX5",
"BuuhV56uRExbLNGNDxnAANXUTyALQLP68r",
"gHJWMRn5UQjinKH9WiFAeeEZ2xDAqHg5f3",
"iUR5yiQuPeYHbtgwkJsR2sQ3rPVUHU9Xwu",
"QYZv4sqMLwLo6AyxcRgSVPcoB1cVQ7yDi6",
"BUqifgUEDA8uLyCta9JQ1zgUqekVgQZx3K",
"EtBne74oGDaNRkJe6mBrGucgdbNjDW5oHw",
"2YQiCbuJXUwNzHFHojL1vDUwKTQYtC6Aakz",
"BYUFQVe5iYD4EBss7xvTLApS5uEB3xMq9W",
"26fhMFMrQc9mjpWhg6SQJXPT28NDDPjkKRQ",
"U49w4TSeWH5HZCFpWa9JmQ3PV8hhJcE9hn",
"2XNVRz4WrBMFheiFL4MbcKYFp6xXVYTZwMj",
"UTmvyT5qPQr4nUmcRSL1qDJLSVizmZxidz",
"Di9qeeg7u454mJeoQKx8HtB4DcHZuXHm7t",
"FandGFeFvZzgQKhgGEV3bSTjrzkF8np3nx",
"2X4611ymA4KNJQ1XAzTZYaEmygS1Xe4tTiM",
"27GpjSYVnee9vRJJu6et9tEYy42ZCfK2RKQ",
"P5q5HsXxFwxmjshLQ6E8QY9fyT9wmrNmgi",
"Xaw1YKF1EdQfChhjGHNrYcg2tnMo3j5Tcu",
"BqsqsdzHydaXbEK1tP2fC2EjJUiwYYPBTZ",
]
