
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/envpprof"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/missinggo"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/utp"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/iter"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/toqueteos/webbrowser"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"
