name: Go

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]

jobs:
    Test:
        name: Do ${{ matrix.test }} tests
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                test: [units, integrations]
        steps:
            - name: Set up Go 1.x
              uses: actions/setup-go@v2
              with:
                  go-version: 1.14

            - name: Check out code into the Go module directory
              uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: 10.16.3

            - name: Test
              env:
                  TEST_SUIT: ${{ matrix.test }}
              run: |
                sudo apt-get update
                sudo apt-get upgrade google-chrome-stable -y
                Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
                ./ci-scripts/lint-and-test.sh
    Build:
        name: Build Wallets
        needs: Test
        runs-on: macos-latest
        steps:
            - name: Set up Go 1.x
              uses: actions/setup-go@v2
              with:
                  go-version: 1.14
            - name: Check out code into the Go module directory
              uses: actions/checkout@v2
            - name: Set up Gox
              run: GO111MODULE=off go get github.com/mitchellh/gox
            - uses: actions/cache@v2
              with:
                path: |
                  ~/Library/Caches/electron
                  ~/Library/Caches/electron-builder
                key: ${{ runner.os }}-electron-${{ hashFiles('./electron/package-lock.json') }}
            - name: Build Wallets
              env:
                OS_NAME: ${{ runner.os }}
                SIGN_BRANCHES: ("refs/heads/master" "refs/heads/develop")
              run: ./ci-scripts/build-wallet.sh
